---
title: "Sketchpad"
author: "Thelonious Goerz"
date: "5/26/2021"
output: html_document
---

```{r, include = F }
# Load data and packages 
library(tidyverse)
library(MASS)
library(nnet)
# Data 
data <- read_csv("./data/bio_a_data_52621.csv")

```

```{r}
# Data cleaning 
# Rename the columns in the data set. ==========================================================
data_clean <- data %>% dplyr :: select(
  # Rename the variables for clean analysis. 
  # Dummy for whether the person is a grad or undergrad 
  student = `Are you a current undergraduate or graduate college student?`,
  # Sexual activity. 
  sex_active = `Are you sexually active?`,
  # Living situation. 
  living_situation = `Please select one of the following that describes your living situation:`,
  # Gender. 
  gender = `What is your Gender?`,
  # Race identity 
  race = `What is your racial identity?`,
  # Hispanic. 
  hispanic = `Are you Hispanic or Latinx?`,
  # Birth year. 
  year_born = `What year were you born? (YYYY)`,
  n_close_friends = `How many close friends do you have that you see or talk to regularly? (Please provide the number e.g. 1,2,3)`,
  # Rate friends covid safety 
  friend_covid_safe = `On a scale of 1-5, with 3 being neutral, how would you rate your close friends' behavior at following COVID-19 safety precautions compared to others?`,
  # Rate your covid safety. 
  resp_covid_safe = `On a scale of 1-5, with 3 being neutral, how would you rate YOUR behavior at following COVID-19 safety precautions, relative to your friends?`,
  # Relationship status. 
  rel_status = `Are you currently in a relationship with another person(s)?`,
  # N sexual partners. 
  n_reg_sex_part = `On a regular basis, how many sexual partners do you have (please count anyone you regularly have sex with)?  (Please provide the number e.g. 1,2,3)`,
  # N drinks per week. 
  n_drinks_week = `On a regular basis, how many drinks per week do you have? (Please provide the number e.g. 1,2,3)`,
  # Sexual activity of friend group. 
  sex_active_friend = `Now, thinking about your friend group, how many of your friends are sexually active?`,
  # What safe sex practices do your friends use. 
  friend_safe_sex = `How many of your friends to the best of your knowledge would you say engage in safe sex practices, eg. using condoms, dental dams, IUD/Birth control, or getting tested for STDs/STIs?`,
  # Share of friends who do not engage in safe sex practices. 
  friend_non_safe_sex = `How many of your friends would you say DO NOT engage in safe sex practices?`,
  # Respondant contraception type. 
  resp_contr_n = `Can you describe the types of protection that you use in your sexual encounters on a regular basis? (such as condoms, dental dams, and IUD/Birth control, or getting tested for STDs/STIs)`,
  # Respondant contraception type. 
  resp_contr_type = `Please describe the protection that you use:`
)

# Filter out people who are not active and are not a student. 
data_clean <- data_clean %>% filter(sex_active != "No" &
                        student != "No")
# Fix variable types 
data_clean <- data_clean %>% 
  mutate(n_close_friends = 
           # Make numeric. 
           as.numeric(n_close_friends), 
         # Fix one level issue on the resp contr type
         resp_contr_type = 
           # Map NA value to no protection. 
           plyr :: mapvalues(resp_contr_type, from = NA, to = "No protection at all"))

```

```{r Response issues with none var in friends questions (if needed), eval = F}
# Clean the variable level names. ==================================
# Look at data. 

# Use if needed with response issues. 

data_clean <- data_clean %>% 
  # Issue with the number of sexually active friends. No option for no friends are sexually active.
  # To fix this I recode NA = none of them, and eliminate responses for other questions that are clearly NA. 
  mutate(sex_active_friend = 
           # Fix levels for NA => recoding NA to none of them. 
           plyr :: mapvalues(sex_active_friend,from = c(NA), 
                             to = ("None of them")),
          # Repeat the procedure with friend safe and non-safe sex. 
         friend_safe_sex = 
           plyr :: mapvalues(friend_safe_sex, from = c(NA), 
                                             to = c("None of them")),
         friend_non_safe_sex = 
           plyr :: mapvalues(friend_non_safe_sex, 
                                                 from = NA, 
                             to = "None of them")
         )

```

```{r}
# Look at the cleaned data. 
data_clean

# When survey is done, save a file with the final raw data and then save a clean file from this file. ================
 # For later. 
```

```{r}
# Look at visual descriptives 
# Living situation. 
ggplot(data = data_clean, aes(x = living_situation)) + 
  geom_bar()

# Gender. 
ggplot(data = data_clean, aes(x = gender)) + 
  geom_bar()

# Race. 
ggplot(data = data_clean, aes(x = race)) + 
  geom_bar()

# Hispanic.
ggplot(data = data_clean, aes(x = hispanic)) + 
  geom_bar()

# Year born. 
ggplot(data = data_clean, aes(x = year_born)) + 
  geom_histogram()

# Close friends. 
ggplot(data = data_clean, aes(x = n_close_friends)) + 
  geom_histogram(stat = "count", 
                 binwidth = 1)

# Friend covid safe. 
ggplot(data = data_clean, aes(x = friend_covid_safe)) + 
  geom_bar()

# Resp covid safe. 
ggplot(data = data_clean, aes(resp_covid_safe)) + 
  geom_bar()

# relationship status. 
ggplot(data = data_clean, aes(rel_status)) + 
  geom_bar()

# N regular sex partners. 
ggplot(data = data_clean, aes(n_reg_sex_part)) + 
  geom_histogram()

# number of drinks a week. 
ggplot(data = data_clean, aes(n_drinks_week)) + 
  geom_histogram()

# Sex active friends 
ggplot(data = data_clean, aes(sex_active_friend)) + 
  geom_bar()

# Friend safe sex. 
ggplot(data = data_clean, aes(friend_safe_sex)) + 
  geom_bar()

# Friend non safe sex 
ggplot(data = data_clean, aes(friend_non_safe_sex)) + 
  geom_bar()

# Respondant contraception number 
ggplot(data = data_clean, aes(resp_contr_n)) + 
  geom_bar()

# Respondant contraception type. 
ggplot(data = data_clean, aes(resp_contr_type)) + 
  geom_bar() 
```




